language: go
go:
- "1.9"
- "1.10"
- "1.11"
env:
  global:
    secure: aYrW+MfufFh4dql1eqmLNSXF8yYDov0FfCa1yMdpotvhLGK+IamlCKJlHMppYnULdHso9QuUKGl0HJAOv6QhBj+UK1BlDuxivJY1KDw2eXSByJeHgD0zgyscAZ2rk0X33K+VQyoT2ieOo3ObiaNqsuhXuGvbjRM8AqOI8IZ6VR7i8xHIFl7DY8/kjPwmD2Vs4ukwpc/Wni0voUM69xC14avJJjJ/9wjMOpxcaRx5k+Ke1NLcImuoDVl2h9DijNZZmTMRmp8qUBPbyVywDS0OSsX8EGHzmEV6f10rs3qjqjXciv37/xiy32vifDulmP5V3TCtcC9Y7vzHGyGFGcYoypi7c8H++lfychbjsMYNJ2iEAwR9m/M1435J1gbDmyKZklRK01EpKvdNnrybM1aSh7pescvRG2tSC8W9kgGyo+1GQr0fkPQdFHWeSCjBtANRr3d5Zq+DzNRo4ZQatfT4Rl0YnAMOVhZvNHZ1NzmzdQHQMZYgxlI4qqLMHuVKgq3PEVOd0KKtFaBQ213+COhvs31OMGs44p/GQkpFYolRJmEzzGOEd0+j6tnTFjuVkhS7gCEYGpUya9Jbyl3UKzfvnTQ7rzayTKErTZg0afajmIEkGLnCDUhFl8WREKnwIwwouPzMlxqe2UWKepYBu9CY6Y1DIWauMlpjpOqDnoW2jAM=

before_install:
- go get github.com/mattn/goveralls

script:
- $HOME/gopath/bin/goveralls -service=travis-ci
